

var webpack = require('webpack');
var path = require('path');

module.exports = {

	//debugging easier
	devtool:
		'inline-source-map',
	

entry:{
	'index':'./src/index.js'
},

output:{
	path: path.resolve(__dirname, 'dist'),
	filename:'main.js'
},

module:{
	rules: [ // multiple rules // inside reate differnt objects 
		{ // babel use garera es6 ,7 es 5 , broser compatible 
				// use babel on which files 
			test:/\.js$/, // regex start with // end -> $ \->characeter escpae
			/*exclude:/node_modules/,*/
			use: 'babel-loader'


		},
		//for css files
		{
			test:/\.css$/,
			exclude:/node_modules/,
		}

	]
},

//devserver to run/serve the application, only in development, node can be used to

devServer:{
	//those content that are not generated by webpack
	contentBase:path.join(__dirname,"public/"),
	port:3027,
	//to serve webpack files
	hot:true,
	publicPath:"http://localhost:3027/dist/"

}


}