

var webpack = require('webpack');
var path = require('path');

module.exports = {

	//debugging easier
	devtool:
		'inline-source-map',
	

entry:{
	'index':'./src/index.js'
},

output:{
	path: path.resolve(__dirname, 'dist'),
	filename:'main.js'
},

module:{
	rules: [ // multiple rules // inside reate differnt objects 
		{ // babel use garera es6 ,7 es 5 , broser compatible 
				// use babel on which files 
			test:/\.js$/, // regex start with // end -> $ \->characeter escpae
			exclude:/node_modules/,
			use: 'babel-loader'


		},
		//for css files
		{
			test:/\.(css|sass)$/,
			// exclude:/node_modules/,
			use:['style-loader','css-loader', 'sass-loader'] // to convert css to js
		// from right first css loader second style loader
		},
		{
			test:/\.(png|jpg|jpeg|svg|gif)$/,
			//use:'file-loader?[name].[ext]'
			//use:'file-loader'

			use:[
			{
				loader:'file-loader',
				options:{
					name:'[path][name].[ext]',
				},
		}

	]
},
{
        test: /\.(woff|woff2|eot|ttf|otf)$/,
		loader: "file-loader"
      },
      {
      test: /\.(jpg|png)$/,
      loader: "url-loader?limit=25000",
      //loader: 'file?name=[path][name].[ext]',
      include: path.join(__dirname, 'public')
    },
]},

//devserver to run/serve the application, only in development, node can be used to

devServer:{
	//those content that are not generated by webpack
	contentBase:path.join(__dirname,"public/"),
	port:3027,
	//to serve webpack files
	hot:true,
	historyApiFallback:true,
	publicPath:"http://localhost:3027/dist/"

}


}
